version: '3'
services:
  api:
    build:
      context: ./api
      dockerfile: .Dockerfile-dev
    ports:
      - "3080:3080"
    container_name: node-api
    volumes:
      - ./api:/usr/src/app/api
      - /usr/src/app/api/node_modules
  angular-ui:
    build:
      context: ./ui
      dockerfile: .Dockerfile-dev
    ports:
      - "4200:4200"
    container_name: angular-ui
    volumes:
      - ./ui:/usr/src/app/ui
      - /usr/src/app/ui/node_modules
  database-api:
    image: postgrest/postgrest
    container_name: database-api
    ports:
      - "3000:3000"
    links:
      - db:db
    environment:
      PGRST_DB_URI: postgres://authenticator:root@db:5432/app_db
      PGRST_DB_SCHEMA: cra_e
      PGRST_DB_ANON_ROLE: postgrestrole #In production this role should not be the same as the one used for the connection
      PGRST_SERVER_PROXY_URI: "http://127.0.0.1:3000"
    depends_on:
      - db
  db:
    image: postgres
    ports:
      - "5432:5432"
    container_name: db
    environment:
      POSTGRES_DB: app_db
      POSTGRES_USER: app_user
      POSTGRES_PASSWORD: password
    volumes:
      - ./database:/usr/src/sql/scripts
    # Uncomment this if you want to persist the data.
    # volumes:
    #   - "./pgdata:/var/lib/postgresql/data"
  swagger:
    image: swaggerapi/swagger-ui
    ports:
      - "8080:8080"
    container_name: swagger
    expose:
      - "8080"
    environment:
      API_URL: http://localhost:3000/
