version: '3'
services:
  api:
    build:
      context: ./api
      dockerfile: .Dockerfile-dev
    ports:
      - "3080:3080"
    container_name: node-api
    volumes:
      - ./api:/usr/src/app/api
      - /usr/src/app/api/node_modules
